package sourcecheck_test

import (
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/iderex/kanzlei/internal/sourcecheck"
)

// The fixtures are a vocabulary of their own rather than a reading of this
// repository. A case that judges the real tree proves what the tree looked like
// on the day it ran; these prove the rule.
func TestABareSuppressionIsRefused(t *testing.T) {
	t.Parallel()

	for name, src := range map[string]string{
		"no linters and no reason": `package p

//nolint
func f() {}
`,
		"linters but no reason": `package p

//nolint:errcheck
func f() {}
`,
		"a list of linters and no reason": `package p

//nolint:errcheck,gosec
func f() {}
`,
		"a label instead of a reason": `package p

//nolint:errcheck // later
func f() {}
`,
		"a staticcheck check with one word after it": `package p

//lint:ignore SA1019 later
func f() {}
`,
		"trailing on the line it suppresses": `package p

func f() int { return 1 } //nolint:errcheck
`,
		"a whole file switched off": `package p

//lint:file-ignore SA1019
func f() {}
`,
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			bare, err := sourcecheck.Bare("fixture.go", []byte(src))
			if err != nil {
				t.Fatalf("Bare: %v", err)
			}
			if len(bare) != 1 {
				t.Fatalf("Bare found %d, want 1: %v", len(bare), bare)
			}
			if bare[0].Line == 0 {
				t.Error("the suppression was reported with no line")
			}
		})
	}
}

func TestASuppressionWithAReasonIsAccepted(t *testing.T) {
	t.Parallel()

	for name, src := range map[string]string{
		"a reason after the linters": `package p

//nolint:errcheck // the error is the authorisation decision and is handled below
func f() {}
`,
		"a reason with no linters named": `package p

//nolint // this file is generated by the schema tool and is not edited here
func f() {}
`,
		"a staticcheck reason": `package p

//lint:ignore SA1019 the replacement landed after the version this pins
func f() {}
`,
		"trailing on the line it suppresses": `package p

func f() int { return 1 } //nolint:errcheck // the caller checks the second return
`,
		"an ordinary comment that is not a suppression": `package p

// f returns one. Nothing here switches anything off.
func f() int { return 1 }
`,
		"a build constraint": `//go:build needsreal

package p

func f() {}
`,
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			bare, err := sourcecheck.Bare("fixture.go", []byte(src))
			if err != nil {
				t.Fatalf("Bare: %v", err)
			}
			if len(bare) != 0 {
				t.Errorf("Bare found %v, want none", bare)
			}
		})
	}
}

// A discarded call result is the suppression the analysers cannot see. The
// defect this is aimed at is the one in the middle: an authorisation decision
// thrown away with the value it decided.
func TestADiscardedCallResultIsRefused(t *testing.T) {
	t.Parallel()

	for name, src := range map[string]string{
		"the whole result": `package p

func g() error { return nil }

func f() {
	_ = g()
}
`,
		"an authorisation decision, error and all": `package p

func may(who, what string) (bool, error) { return false, nil }

func f() bool {
	allowed, _ := may("a", "b")
	return allowed
}
`,
		"both results of a two-value call": `package p

func g() (int, error) { return 0, nil }

func f() {
	_, _ = g()
}
`,
		"a reason too short to be one": `package p

func g() error { return nil }

func f() {
	_ = g() // later
}
`,
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			bare, err := sourcecheck.Bare("fixture.go", []byte(src))
			if err != nil {
				t.Fatalf("Bare: %v", err)
			}
			if len(bare) != 1 {
				t.Fatalf("Bare found %d, want 1: %v", len(bare), bare)
			}
		})
	}
}

func TestADiscardWithAReasonIsAccepted(t *testing.T) {
	t.Parallel()

	for name, src := range map[string]string{
		"a reason on the line": `package p

func g() error { return nil }

func f() {
	_ = g() // cleanup after the case has already reported, where this changes no verdict
}
`,
		"a blank that is not the last value": `package p

func g() (int, string, error) { return 0, "", nil }

func f() error {
	_, s, err := g()
	_ = s
	return err
}
`,
		"a blank on something that is not a call": `package p

func f(m map[string]int) bool {
	_, ok := m["k"]
	return ok
}
`,
		"a type assertion": `package p

func f(v any) bool {
	_, ok := v.(string)
	return ok
}
`,
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			bare, err := sourcecheck.Bare("fixture.go", []byte(src))
			if err != nil {
				t.Fatalf("Bare: %v", err)
			}
			if len(bare) != 0 {
				t.Errorf("Bare found %v, want none", bare)
			}
		})
	}
}

func TestEverySuppressionInTheFileIsReported(t *testing.T) {
	t.Parallel()

	const src = `package p

//nolint
func a() {}

//nolint:errcheck // this one says why it is here and stays
func b() {}

//lint:ignore SA1019
func c() {}
`

	bare, err := sourcecheck.Bare("fixture.go", []byte(src))
	if err != nil {
		t.Fatalf("Bare: %v", err)
	}
	if len(bare) != 2 {
		t.Fatalf("Bare found %d, want 2: %v", len(bare), bare)
	}
	// Reporting only the first would make the fix a loop: run, fix one, run
	// again, for as many as the file holds.
	if bare[0].Line == bare[1].Line {
		t.Errorf("both reports name line %d", bare[0].Line)
	}
}

func TestASourceFileThatDoesNotParseIsAnError(t *testing.T) {
	t.Parallel()

	// Failing closed. A file this cannot read is a file whose suppressions it
	// cannot see, and reporting none would read as a clean file.
	if _, err := sourcecheck.Bare("fixture.go", []byte("package")); err == nil {
		t.Fatal("an unparseable file was reported as holding no suppressions")
	}
}

// TestABlockCommentIsNotRead states a limit rather than a behaviour. No
// analyser reads a directive out of a block comment, so neither does this, and
// somebody who writes one gets no suppression and no complaint.
func TestABlockCommentIsNotRead(t *testing.T) {
	t.Parallel()

	const src = `package p

/* nolint */
func f() {}
`

	bare, err := sourcecheck.Bare("fixture.go", []byte(src))
	if err != nil {
		t.Fatalf("Bare: %v", err)
	}
	if len(bare) != 0 {
		t.Errorf("Bare read a block comment: %v", bare)
	}
}

// TestThisRepositoryHoldsNoBareSuppression is the reading of the real tree, and
// it proves the state of the tree rather than the rule. Both are wanted: the
// cases above are what the check is, and this is what it currently says.
func TestThisRepositoryHoldsNoBareSuppression(t *testing.T) {
	t.Parallel()

	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("locate the repository root: %v", err)
	}

	bare, err := sourcecheck.BareInTree(root)
	if err != nil {
		t.Fatalf("BareInTree: %v", err)
	}
	if len(bare) != 0 {
		var b strings.Builder
		for _, s := range bare {
			fmt.Fprintf(&b, "\n  %s", s)
		}
		t.Errorf("%d suppression(s) with no reason:%s", len(bare), b.String())
	}
}
